Traceback (most recent call last):
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 224, in main
    assert ts == model.last_ts + PERIOD
AssertionError
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 260, in <module>
    main(models, now)
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 236, in main
    raise e
  File "/root/curve-lp-metrics/curvemetrics/scripts/forever.py", line 224, in main
    assert ts == model.last_ts + PERIOD 
AssertionError
